In [20]:
#Saving Final model
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('insurance_pre.csv')
dataset = pd.get_dummies(dataset,drop_first=True)
#identifying inputs
input_var=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
#identifying output
output_var=dataset['charges']
#split into training set and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(input_var,output_var,test_size=1/3, random_state=0)
#we are going to standardization to enhance the model training
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
#fit_transform will train model with standardization
x_test=sc.transform(x_test)
x_test

array([[ 0.89108031, -0.07576237, -0.0755796 ,  1.01127431, -0.49929923],
       [ 0.5336223 , -0.21009861, -0.0755796 , -0.98885138, -0.49929923],
       [ 0.6051139 ,  1.60182214,  0.75672907,  1.01127431,  2.00280702],
       ...,
       [-1.46814257,  0.65256665,  0.75672907, -0.98885138,  2.00280702],
       [-0.82471815,  0.37742013,  1.58903774,  1.01127431, -0.49929923],
       [ 0.89108031,  1.24817794,  0.75672907, -0.98885138, -0.49929923]])

In [23]:
#i_age=25
#i_bmi=26
#i_children=3
#i_sex_male=0
#i_smoker_yes=1
#input_1=[25,26,3,0,1]
#preinput=sc.transform([[25,26,3,0,1]])
#preinput=sc.transform([[i_age,i_bmi,i_children,i_sex_male,i_smoker_yes]])
#preinput=sc.transform([input_1])
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:25
BMI:26
Children:3
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1


In [24]:
preinput=sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

C:\anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [27]:
#Insurance_chrg_Pred_model_Deployment_Script
import pickle
#filename="RF_n75_insurance_chrg_pred_model.pkl"
filename="insurance_chrg_pred_final_model.pkl"
loaded_model=pickle.load(open(filename,'rb'))

In [26]:
preinput

array([[-1.03919296, -0.75553612,  1.58903774, -0.98885138,  2.00280702]])

In [3]:
#Pre-Process  the input before passing

In [30]:
result=loaded_model.predict(preinput) #Testing 
result


array([19629.67289475])